name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Up Go
        uses: actions/setup-go@v3
      - name: Build Go
        run: go build -v ./...
      - name: Test Go
        run: go test -v ./...
